name: Deploy to Hostinger

on:
  push:
    branches:
      - master  # Change this to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Update to Node.js version 16

      - name: Install dependencies
        run: npm install

      - name: Build Vue.js app
        run: npx vue-cli-service build

      - name: Deploy to Hostinger
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 145.14.153.167
          username: server659
          key: SHA256:rQpvp/RzLSNFoeGqM6nhNJY1Is5w59S6CQXGzVEDe/U arlindaliu08@gmail.com
          script: |
            cd /public_html/luliflex
            git pull origin master
        env:
          SSH_PRIVATE_KEY: fgasdf2sdg2t34wedfDdF)R221
